import { google, type docs_v1 } from 'googleapis'
import type { AuthProvider } from '../auth/types.js'

/** Reads only. Repair requests, when they exist, are generated by emit/ like everything else. */

export async function fetchDocument(
  auth: AuthProvider,
  documentId: string,
): Promise<docs_v1.Schema$Document> {
  const docs = google.docs({ version: 'v1', auth: await auth.client() })
  const res = await docs.documents.get({ documentId, includeTabsContent: true })
  return res.data
}

/**
 * With includeTabsContent the content hangs off document.tabs[].documentTab; without it, off
 * document.body. Handle both so callers do not have to care.
 */
export function bodies(doc: docs_v1.Schema$Document): docs_v1.Schema$Body[] {
  const fromTabs = (tabs: docs_v1.Schema$Tab[] | undefined): docs_v1.Schema$Body[] =>
    (tabs ?? []).flatMap((tab) => [
      ...(tab.documentTab?.body ? [tab.documentTab.body] : []),
      ...fromTabs(tab.childTabs),
    ])

  const tabBodies = fromTabs(doc.tabs)
  if (tabBodies.length > 0) return tabBodies
  return doc.body ? [doc.body] : []
}

/**
 * One specific tab's own body, for when a caller needs to reconstruct indices within a single tab
 * rather than treat the whole (multi-tab) document as one flattened sequence — `bodies()` merges
 * every tab together, which is wrong once tabs mean separate, independently-indexed documents.
 */
export function tabBody(
  doc: docs_v1.Schema$Document,
  tabId: string,
): docs_v1.Schema$Body | undefined {
  function search(tabs: docs_v1.Schema$Tab[] | undefined): docs_v1.Schema$Body | undefined {
    for (const tab of tabs ?? []) {
      if (tab.tabProperties?.tabId === tabId) return tab.documentTab?.body
      const found = search(tab.childTabs)
      if (found) return found
    }
    return undefined
  }
  return search(doc.tabs)
}

export interface RunInfo {
  text: string
  font: string | undefined
  sizePt: number | undefined
  bold: boolean | undefined
  namedStyleType: string | undefined
  startIndex: number | undefined
}

export function describeRuns(doc: docs_v1.Schema$Document): RunInfo[] {
  const runs: RunInfo[] = []
  for (const body of bodies(doc)) {
    for (const element of body.content ?? []) {
      const paragraph = element.paragraph
      if (!paragraph) continue
      const namedStyleType = paragraph.paragraphStyle?.namedStyleType ?? undefined
      for (const child of paragraph.elements ?? []) {
        const run = child.textRun
        if (!run?.content) continue
        runs.push({
          text: run.content,
          font: run.textStyle?.weightedFontFamily?.fontFamily ?? undefined,
          sizePt: run.textStyle?.fontSize?.magnitude ?? undefined,
          bold: run.textStyle?.bold ?? undefined,
          namedStyleType,
          startIndex: child.startIndex ?? undefined,
        })
      }
    }
  }
  return runs
}

/** Proves updateNamedStyle actually took effect — the definitions come back in documents.get. */
export function namedStyleSummary(
  doc: docs_v1.Schema$Document,
): Array<{ type: string; font?: string; sizePt?: number; bold?: boolean }> {
  const fromTab = doc.tabs?.[0]?.documentTab?.namedStyles?.styles
  const styles = fromTab ?? doc.namedStyles?.styles ?? []
  return styles.map((style) => ({
    type: style.namedStyleType ?? '(unknown)',
    font: style.textStyle?.weightedFontFamily?.fontFamily ?? undefined,
    sizePt: style.textStyle?.fontSize?.magnitude ?? undefined,
    bold: style.textStyle?.bold ?? undefined,
  }))
}

export function countParagraphs(doc: docs_v1.Schema$Document): number {
  return bodies(doc).reduce(
    (total, body) => total + (body.content ?? []).filter((e) => e.paragraph).length,
    0,
  )
}

/**
 * The headline requirement as an assertion: no MARKDOWN SYNTAX may survive into the document text.
 * That is narrower than "these characters never appear" — real content legitimately contains `**`
 * (Python kwargs), backticks, and `|` (shell pipes, enum-style values, diagram edge labels) once it's
 * inside a code span, and the corpus has all three. A run is treated as code, and exempted from the
 * character-content checks, when it carries `codeFont` — the only way a run gets that font in this
 * milestone is the 'code' inline mark (see emit/inline.ts), covering both genuine inline code and
 * M1's degraded fenced-code-per-line paragraphs.
 *
 * The two ANCHORED checks (a line starting with `#` or a list marker) are evaluated once per
 * paragraph, against the paragraph's full text — never per inline-styled run. A run boundary falls
 * wherever styling changes, which is very often mid-sentence (e.g. "`eligible` + insights score");
 * checking every run's start against a start-of-line pattern flags ordinary prose that happens to
 * follow a styled span with a literal "+" or "-".
 */
export function residueFindings(doc: docs_v1.Schema$Document, opts: { codeFont: string }): string[] {
  const contentPatterns: Array<[RegExp, string]> = [
    [/\*\*/, 'bold markers (**)'],
    [/`/, 'backticks'],
    [/\|.*\|/, 'table pipes (|)'],
  ]
  const anchoredPatterns: Array<[RegExp, string]> = [
    [/^\s*#{1,6}\s/, 'ATX heading markers (#)'],
    [/^\s*[-*+]\s/, 'unconverted list markers'],
  ]

  const isCode = (run: docs_v1.Schema$TextRun): boolean =>
    run.textStyle?.weightedFontFamily?.fontFamily === opts.codeFont

  const findings: string[] = []
  for (const body of bodies(doc)) {
    for (const element of body.content ?? []) {
      const paragraph = element.paragraph
      if (!paragraph) continue
      const runs = (paragraph.elements ?? [])
        .map((el) => el.textRun)
        .filter((r): r is docs_v1.Schema$TextRun => Boolean(r?.content))
      if (runs.length === 0) continue

      if (!isCode(runs[0]!)) {
        const fullText = runs.map((r) => r.content).join('')
        for (const [pattern, label] of anchoredPatterns) {
          if (pattern.test(fullText)) {
            findings.push(`${label} in ${JSON.stringify(fullText.slice(0, 60))}`)
          }
        }
      }

      for (const run of runs) {
        if (isCode(run)) continue
        for (const [pattern, label] of contentPatterns) {
          if (pattern.test(run.content!)) {
            findings.push(`${label} in ${JSON.stringify(run.content!.slice(0, 60))}`)
          }
        }
      }
    }
  }
  return findings
}
